- path: /releases/name=mattermost/url
  type: replace
  value: "https://s3.amazonaws.com/mattermost-boshrelease/compiled-releases/mattermost-6.4.2-ubuntu-trusty-3541.12-20180427-220121-332745829-20180427220134.tgz"
- path: /releases/name=mattermost/version
  type: replace
  value: "6.4.2"
- path: /releases/name=mattermost/sha1
  type: replace
  value: "60f289c4f9c90e7ff9c099f0d9bf201fe8f26595"

- path: /releases/name=mattermost/stemcell?
  type: replace
  value:
    os: "ubuntu-trusty"
    version: "3541.12"
