- path: /releases/name=mattermost/url
  type: replace
  value: "https://s3.amazonaws.com/mattermost-boshrelease/compiled-releases/mattermost-6.4.0-ubuntu-trusty-3541.12-20180415-172358-446667812-20180415172408.tgz"
- path: /releases/name=mattermost/version
  type: replace
  value: "6.4.0"
- path: /releases/name=mattermost/sha1
  type: replace
  value: "4312de2c1860f42ca8e2223aba611ea3462e833e"

- path: /releases/name=mattermost/stemcell?
  type: replace
  value:
    os: "ubuntu-trusty"
    version: "3541.12"
