---
platform: linux
image: docker:///concourse/concourse-ci

inputs:
- {name: boshrelease}
- {name: cf-cli}

outputs:
- {name: imagedir}

run:
  path: ./boshrelease/ci/tasks/build-imagedir.sh
  args: []
