---
platform: linux
image: docker:///starkandwayne/mattermost-boshrelease-pipeline

inputs:
- {name: boshrelease}

outputs:
- {name: sql-service}

params:
  cf_username:
  cf_password:
  cf_org:
  cf_space: mattermost-test
  cf_service_name: cf-sql


run:
  path: boshrelease/ci/tasks/create-sql-service.sh
