---
platform: linux
image: docker:///starkandwayne/mattermost-boshrelease-pipeline

inputs:
- {name: boshrelease, path: .}
- {name: create-sql-service, path: tmp/sql-service}


params:
  bosh_target:
  bosh_username: admin
  bosh_password: admin

run:
  path: ci/tasks/upload-dev-release.sh
