---
mattermost/mattermost-1.2.0.tar.gz:
  object_id: d3abc43b-0e6a-4bc0-a755-153717321119
  sha: !binary |-
    MzI1NWNkYTRmYjBlZTA0YjFhNzBlYTE2NTZjMzEzNDJmZTM1OTU3Yw==
  size: 15480507
mattermost/mattermost-1.2.1.tar.gz:
  object_id: 2a58b630-5177-4ccb-afb3-9a3b606609e4
  sha: !binary |-
    MWMxY2JkNzJkN2E5ZWU1OGVkYWEwYjM4YTlkZDFmNTRmMjZlYzYwZQ==
  size: 15501089
