meta:
  stemcell: (( params "please provide meta.stemcell details" ))

name: (( params "please provide a deployment 'name'" ))

director_uuid: (( params "please provide director_uuid" ))

releases:
  - name: mattermost
    version: latest
  - name: route-registrar
    version: latest

networks: (( params "please provide networks" ))

jobs: (( params "please provide jobs" ))

properties: {}

compilation:
  workers: 6
  network: mattermost_platform1
  reuse_compilation_vms: true
  cloud_properties: (( params "please provide compilation.cloud_properties" ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: small_z1
    network: mattermost_platform1
    stemcell: (( meta.stemcell ))
    cloud_properties: (( params "please provide resource_pools.small_z1.cloud_properties" ))
