name: mattermost-warden

meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: mattermost
    networks:
      - name: mattermost_platform1
    properties:
      route_registrar:
        external_host: mattermost.10.244.0.34.xip.io
        message_bus_servers:
        - host: 10.244.0.6:4222
          user: nats
          password: nats

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: mattermost_platform1
  type: manual
  subnets:
  - range: 10.244.30.0/24
    name: mattermost_platform1
    gateway: 10.244.30.1
    static:
      - 10.244.30.2-10.244.30.60
