update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: mattermost
    templates:
    - name: mattermost
      release: mattermost-platform
    - name: route-registrar
      release: route-registrar
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( params "please provide jobs.mattermost.networks" ))
    properties:
      mattermost:
        sql:
          driver_name: postgres
          url: (( params "please provide DB url, such as postgres://mmuser:mmuser_password@10.10.10.1:5432/mattermost?sslmode=disable&connect_timeout=10"))
          max_connections: 10
          at_rest_encrypt_key: 7rAh6iwQCkV4cA1Gsg3fgGOXJAQ43QVg
      route_registrar:
        external_host: (( params "please provide properties.route_registrar.external_host to advertise as the route"))
        port: 8065
        health_checker:
          name: mattermost
        message_bus_servers:
          - host: (( params "please provide at least one NATS host"))
            user: (( params "please provide at least one NATS user"))
            password: (( params "please provide at least one NATS password"))
