---
groups:
- name: build
  jobs: [bump, testflight, shipit]
- name: image
  jobs: [task-image]

jobs:
- name: bump
  public: true
  plan:
  - aggregate:
    - get: mattermost
      trigger: true
      params:
        globs: [mattermost*]
    - {get: boshrelease}
  - task: bump-blob
    file: boshrelease/ci/tasks/bump-blob.yml
    config:
      params:
        aws_access_key_id: {{blobstore-aws-accesss}}
        aws_secret_access_key: {{blobstore-aws-secret}}
  - put: boshrelease
    params: {repository: bump-blob, rebase: true}

- name: testflight
  serial: true
  plan:
  - {get: boshrelease, trigger: true}
  - task: create-sql-service
    file: boshrelease/ci/tasks/create-sql-service.yml
    config:
      params:
        cf_username: {{cf-username}}
        cf_password: {{cf-password}}
        cf_org: {{cf-org}}
        cf_space: {{cf-space}}
        cf_service_name: ci-sql
  - task: upload-dev-release
    file: boshrelease/ci/tasks/upload-dev-release.yml
    config:
      params:
        bosh_target: {{bosh-lite-target}}
        bosh_username: {{bosh-lite-username}}
        bosh_password: {{bosh-lite-password}}

- name: shipit
  public: true
  serial: true
  plan:
  - get: boshrelease
    passed: [testflight]
  - task: create-final-release
    file: boshrelease/ci/tasks/create-final-release.yml
    config:
      params:
        aws_access_key_id: {{blobstore-aws-accesss}}
        aws_secret_access_key: {{blobstore-aws-secret}}
        bosh_target: {{bosh-lite-target}}
        bosh_username: {{bosh-lite-username}}
        bosh_password: {{bosh-lite-password}}
  - put: boshrelease
    params:
      repository: final-release
      rebase: true

- name: task-image
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: boshrelease}
    - {get: boshrelease-image, trigger: true}
    - {get: cf-cli, trigger: true}
  - task: build-imagedir
    file: boshrelease/ci/tasks/build-imagedir.yml
  - put: task-image
    params:
      build: imagedir

resources:
- name: boshrelease
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/mattermost-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}

- name: boshrelease-image
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/mattermost-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    globs: [ci/image/*]

- name: cf-cli
  type: s3
  source:
    bucket: go-cli
    regexp: releases/v(.*)/cf-cli_.*_linux_x86-64.tgz

- name: task-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: starkandwayne/mattermost-boshrelease-pipeline

- name: mattermost
  type: github-release
  source:
    user: mattermost
    repository: platform
    access_token: {{github-access-token}}

- name: boshrelease-image-pg94
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/postgresql-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/postgresql94/*]

- name: boshrelease-image-pg95
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/postgresql-docker-boshrelease.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/postgresql95/*]
